class CONSTANTS:
    STARTING_CUSTOMERS = 10
    CUSTOMER_MAX_ITEMS = 30

    REGULAR_LANE_MAX_CUSTOMERS = 5
    REGULAR_LANE_ITEM_PROCESS_SECS = 4

    SELF_CHECKOUT_MAX_CUSTOMERS = 15
    SELF_CHECKOUT_MAX_ITEMS = 9
    SELF_CHECKOUT_TILLS = 8
    SELF_CHECKOUT_ITEM_PROCESS_SECS = 6

    CUSTOMER_WAVES = 5
    MAX_CUSTOMERS = 40
    MAX_NEW_CUSTOMERS_PER_WAVE = 5
    CUSTOMER_WAVE_INTERVAL_SECS = 30

    REPORT_INTERVAL_SECS = 30
